accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'


urlpatterns = [
        url(r'^register/$', views.register_user, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^where/should/admin/go/to/be/safe/', admin.site.urls),
    url(r'^account/', include('accounts.urls')),
    url(r'^comment/', include('comments.urls')),
    url(r'^', include('posts.urls')),
]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'


urlpatterns = [
    url(r'^post/new/$', views.post_create, name='post_create'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='post_detail'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='post_update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^post/draft/$', views.post_draft, name="post_draft"),
    url(r'^post/published/$', views.post_published, name="post_published"),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.utils.safestring import mark_safe

from comments.models import Comment

from markdown_deux import markdown

# Create your models here.

class PostManager(models.Manager):

    def active(self, *args, **kwargs):
        qs = super(PostManager, self).filter(draft=False)
        return qs

    def all_of_user(self, user, *args, **kwargs):
        qs = super(PostManager, self).filter(
                        (models.Q(user=user) & models.Q(draft=True)) |
                        models.Q(draft=False)
                        ).distinct()
        return qs


def upload_location(instance, filename):
    #new post or first post
    try:
        new_id = Post.objects.all().last().id +1
    except:
        new_id = 1
    #for post update
    try:
        if instance.id:
            new_id = instance.id
    except:
        pass

    return "{}/{}".format(new_id, filename)


class Post(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=180)
    content = models.TextField()
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    slug = models.SlugField(unique=True)
    draft = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    objects = PostManager()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"slug":self.slug, })

    def get_marked_content(self):
        return mark_safe(markdown(self.content))

    class Meta():
        ordering = ["-update"]


    @property
    def get_content_type(self):
        qs = ContentType.objects.get_for_model(self.__class__)
        return qs

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs




def create_slug(instance, new_slug=None):
    if new_slug:
        slug = new_slug
    else:
        slug = slugify(instance.title)

    check_slug = Post.objects.filter(slug=slug)
    if check_slug.exists():
        slug = "{}-{}".format(slug, check_slug.last().id )
        slug = create_slug(instance, slug)
    return slug

def pre_save_post_receiver(instance, sender, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

accounts/forms.py
from django import forms
from django.contrib.auth import ( authenticate,
                                    login,
                                    logout,
                                    get_user_model,
                                    )


User = get_user_model()

class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email Address")
    email2 = forms.EmailField(label="Confirm email")
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = [ "first_name",
                    "last_name",
                    "username",
                    "email",
                    "email2",
                    "password",
                    ]


    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")

        if email != email2:
            raise forms.ValidationError("Email does not match.")

        check_email = User.objects.filter(email=email)
        if check_email.exists():
            raise forms.ValidationError("This email is already registered with us.")

        return email



class SuperuserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email Address")
    email2 = forms.EmailField(label="Confirm email")
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = [ "first_name",
                    "last_name",
                    "username",
                    "is_staff",
                    "email",
                    "email2",
                    "password",
                    ]


    def clean_email2(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")

        if email != email2:
            raise forms.ValidationError("Email does not match.")

        check_email = User.objects.filter(email=email)
        if check_email.exists():
            raise forms.ValidationError("This email is already registered with us.")

        return email




class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        user = authenticate(username=username, password=password)

        if not user:
            raise forms.ValidationError("Invalid username and password.")
        if not user.is_active:
            raise forms.ValidationError("This account is not active.")

        return super(LoginForm, self).clean(*args, **kwargs)

posts/forms.py
from django import forms

from .models import Post

from pagedown.widgets import PagedownWidget



class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))

    class Meta():
        model = Post
        fields = ["title", "content", "image", "draft"]

accounts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import ( authenticate,
                                    login,
                                    logout,)
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import RegisterForm, LoginForm, SuperuserRegisterForm
# Create your views here.



def register_user(request):
    if request.user.is_authenticated() and not request.user.is_superuser:
        return HttpResponseRedirect(reverse("posts:post_list"))

    form = RegisterForm(request.POST or None)
    if request.user.is_superuser:
        form = SuperuserRegisterForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.set_password(form.cleaned_data.get("password"))
        instance.save()
        messages.success(request, "User registered successfully.")
        if request.user.is_superuser:
            return HttpResponseRedirect(reverse("accounts:register"))
        return HttpResponseRedirect(reverse("accounts:login"))

    context = {
        "form":form,
        "title": "Register"
    }

    return render(request, "account_form.html", context)



def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse("posts:post_list"))

    form = LoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                next_page = request.GET.get("next")
                messages.success(request, "You are successfully logged in.")
                if next_page:
                    return HttpResponseRedirect(next_page)
                return HttpResponseRedirect(reverse("posts:post_list"))
            else:
                messages.error(request, "Your account is no longer active.")
        else:
            messages.error(request, "Invalid credentials")

    context = {
        "title": "Login",
        "form": form,
    }

    return render(request, "account_form.html", context)


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "You are successfully logged out.")
    return HttpResponseRedirect(reverse("accounts:login"))

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
# from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType

from comments.forms import CommentForm
from comments.models import Comment

from .forms import PostForm
from .models import Post
# Create your views here.



def post_list(request):
    object_list = Post.objects.active()
    if request.user.is_superuser:
        object_list = Post.objects.all()
    elif request.user.is_staff:
        object_list = Post.objects.all_of_user(request.user)

    #search functionality
    query_list = []
    q = request.GET.get("q")
    if q:
        query = q.split()
        for q in query:
            query_list += object_list.filter(
                Q(title__icontains=q) |
                Q(content__icontains=q) |
                Q(user__username__icontains=q) |
                Q(slug__icontains=q)
            ).distinct()
        object_list = query_list


    paginator = Paginator(object_list, 5)

    page = request.GET.get("p")

    try:
        objects = paginator.page(page)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        objects = paginator.page(1)

    context = {
        "objects": objects,
        "title": "All posts",
    }

    return render(request, "post_list.html", context)



@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('accounts:login'))
def post_create(request):

    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        print(form.cleaned_data)
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Post successfully created.")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Create New Post",
        "form": form,
    }

    return render(request, "post_form.html", context)




def post_detail(request, slug):
    instance = get_object_or_404(Post, slug=slug)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id,
    }

    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid():
        c_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        object_id = int(comment_form.cleaned_data.get("object_id"))
        content = comment_form.cleaned_data.get("content")
        parent_obj = None
        user = request.user

        parent_id = request.POST.get("parent_id")
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs and parent_qs.count()==1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                                content=content,
                                parent=parent_obj,
                                content_type=content_type,
                                object_id=object_id,
                                user=user,
                            )

        if created:
            messages.success(request, "Comment successfully submitted.")
            return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
        else:
            messages.error(request, "Some error occured, comment cannot be posted.")
            return HttpResponseRedirect(instance.get_absolute_url())


    context = {
        "title": instance.title,
        "instance": instance,
        "comment_form": comment_form,
    }

    return render(request, "post_detail.html", context)




@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('accounts:login'))
def post_update(request, slug):
    instance = get_object_or_404(Post, slug=slug)
    if instance.user != request.user and not request.user.is_superuser:
        messages.error(request, "You are not the author of this post.")
        return HttpResponseRedirect(instance.get_absolute_url())
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)

    if form.is_valid():
        print(form.cleaned_data)
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Post successfully updated.")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Update Post",
        "form": form,
    }

    return render(request, "post_form.html", context)




@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('accounts:login'))
def post_delete(request, slug):
    instance = get_object_or_404(Post, slug=slug)

    if instance.user != request.user and not request.user.is_superuser:
        messages.error(request, "You cannot delete this post as you are not the author.")
        return HttpResponseRedirect(instance.get_absolute_url())

    response = request.POST.get("response")
    if response == "Yes":
        instance.delete()
        messages.success(request, "Post successfully deleted.")
        return HttpResponseRedirect("/")
    elif response == "No":
        messages.warning(request, "Post deletion cancelled.")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
    }

    return render(request, "post_delete.html", context)



@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('accounts:login'))
def post_draft(request):

    object_list = Post.objects.all_of_user(request.user).filter(draft=True)
    if request.user.is_superuser:
        object_list = Post.objects.all().filter(draft=True)

    paginator = Paginator(object_list, 5)

    page = request.GET.get("p")

    try:
        objects = paginator.page(page)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        objects = paginator.page(1)

    context = {
        "objects": objects,
        "title": "All Drafts",
    }

    return render(request, "post_list.html", context)




@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('accounts:login'))
def post_published(request):

    object_list = Post.objects.all_of_user(request.user).filter(draft=False)
    if request.user.is_superuser:
        object_list = Post.objects.all().filter(draft=False)

    paginator = Paginator(object_list, 5)

    page = request.GET.get("p")

    try:
        objects = paginator.page(page)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        objects = paginator.page(1)

    context = {
        "objects": objects,
        "title": "All published posts",
    }

    return render(request, "post_list.html", context)

templates/account_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block body %}

<div class="col-sm-6 col-sm-offset-3">

  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="{{ title }}">
  </form>
  
</div>



{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>

    {% include "css_files.html" %}

    {% block head_extra %}{% endblock %}
  </head>
  <body>

    {% include "navbar.html" %}

    <div class="container">
      {% include "messages.html" %}

      {% block body %}{% endblock %}
    </div>



    {% include "js_files.html" %}

    {% block body_extra %}{% endblock %}

    <script type="text/javascript">
      $(document).ready(function(){
        $("img").each(function(){
          $(this).addClass("img-responsive")
        })
      });
    </script>
  </body>
</html>

templates/comment_delete.html
{% extends "base.html" %}


{% block title %}{{ title }}{% endblock %}



{% block body %}

<div class="col-sm-6 col-sm-offset-3">
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure, you want to delete <strong>{{ instance.content}}</strong> ?</p>
      <input type="submit" name="response" value="No" class="btn btn-primary">
      <input type="submit" name="response" value="Yes" class="btn btn-danger">
    </form>
  </div>  
</div>


{% endblock %}

templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}


{% block body %}


<div class="col-sm-6 col-sm-offset-3">

  <h1><a href="{{ comment.content_object.get_absolute_url }}">{{ title }}</a></h1>

  <div class="comments">

      <div class="jumbotron">
        <p class="comment-content">{{ comment.content }}</p>
        <footer>
          by <strong>{{ comment.user|capfirst }}</strong>{%if comment.user == comment.content_object.user%}<span class="badge">AUTH</span>{%endif%}
           | {{ comment.timestamp|timesince }} ago |
          {% if comment.children %}
          {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{%endif%} |
          {% endif %}
          {% if comment.user == request.user or request.user.is_superuser or comment.content_object.user == request.user %}
            <a href="{{ comment.get_delete_url }}">Delete</a>
          {% endif %}
        </footer>
      </div>



      {% if comment.children %}
        <div class="comment-reply-thread">
        {% for child_comment in comment.children %}
          <blockquote>
            {{ child_comment.content }}
            <footer>
              by <strong>{{ child_comment.user|capfirst }}</strong>{%if child_comment.user == child_comment.content_object.user%}<span class="badge">AUTH</span>{%endif%}
               | {{ child_comment.timestamp|timesince }} ago
              {% if child_comment.user == request.user or request.user.is_superuser %}
              | <a href="{{ child_comment.get_delete_url }}">Delete</a>
              {% endif %}
            </footer>
          </blockquote>
        {% endfor %}
      {% endif %}

      </blockquote>
      <form method="post">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input type="hidden" name="parent_id" value="{{ comment.id }}">
        <input class="btn btn-primary" type="submit" value="Reply">
      </form>
      </div>

  </div>

</div>

{% endblock %}

templates/css_files.html
{% load staticfiles %}

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<link rel="stylesheet" href="{% static "css/master.css" %}">

<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

templates/js_files.html
<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" charset="utf-8"></script>

templates/messages.html
<div class="col-sm-6 col-sm-offset-3">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     {{ message }}
  </div>
  {% endfor %}
  {% endif %}
</div>

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">My Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <!-- <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul> -->
        </li>
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated and user.is_staff %}
        <li><a href="{% url 'posts:post_create' %}">New Post</a></li>
        <li><a href="{% url 'posts:post_published' %}">Published</a></li>
        <li><a href="{% url 'posts:post_draft' %}">Drafts</a></li>
        {% endif %}

      </ul>

      <form class="navbar-form navbar-left" action="{% url 'posts:post_list' %}" method="GET">
        <div class="input-group">
          <input type="text" class="form-control" name="q" placeholder="Search">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default">Search</button>
          </span>
        </div>
      </form>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="https://github.com/thevivekshukla/django-blog" target="_blank" style="color:red;">Fork on github</a></li>
        {% if user.is_superuser %}
        <li><a href="{% url "accounts:register" %}"><span class="glyphicon glyphicon-user"></span> Add user</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
        <li><a href="{% url "accounts:register" %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="{% url "accounts:login" %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% else %}
        <li><a href="#">User: {{ user.username }}</a></li>
        <li><a href="{% url "accounts:logout" %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

templates/post_delete.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block body %}


<div class="col-sm-6 col-sm-offset-3">
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      <p>Do you really want to delete the post with title
        "{{ instance.title }}" and id {{instance.id}}?</p>
      <input class="btn btn-primary" type="submit" name="response" value="No">
      <input class="btn btn-danger" type="submit" name="response" value="Yes">
    </form>
  </div>
</div>



{% endblock %}

templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block meta %}

<meta name="description" content="{{ instance.content|truncatechars:160 }}">
<meta name="author" content="{{ instance.user.username }}">

{% endblock %}


{% block body %}


<div class="col-sm-8 col-sm-offset-2">
  <h1>{{ instance.title|capfirst }}</h1>
  <small><strong>Updated: </strong>{{ instance.update|timesince }} ago </small>
  <small><strong> Author: {{ instance.user.username|capfirst }}</strong></small>
  {% if instance.user == request.user or request.user.is_superuser %}
  <small><a href="{% url 'posts:post_update' slug=instance.slug %}"><span class="glyphicon glyphicon-pencil"></span> Edit</a></small>
  <small><a href="{% url 'posts:post_delete' slug=instance.slug %}"><span class="glyphicon glyphicon-trash"></span> Delete</a></small>
  {% endif %}
  <br><br>
  {% if instance.image %}
  <p><img class="img img-responsive" src="{{ instance.image.url }}" alt=""></p>
  {% endif %}
  <br><br>
  <div class="post-content">{{ instance.get_marked_content }}</div>

  <br><hr>


  <div class="comments">
    <span class="lead"><h2>Comments</h2></span>
    {% if user.is_authenticated %}
    <form method="post">
      {% csrf_token %}
      {{ comment_form|crispy }}
      <input class="btn btn-primary" type="submit" value="Comment">
    </form>
    {% else %}
    <p>You must be logged in comment.</p>
    {% endif %}
    <br>

    {% if instance.comments %}

    {% for comment in instance.comments %}
      <blockquote>
        {{ comment.content }}

        <footer>
          by <strong>{{ comment.user|capfirst }}</strong>{%if comment.user == instance.user%}<span class="badge">AUTH</span>{%endif%} |
          {{ comment.timestamp|timesince }} ago |
          {% if comment.children %}
          <a class="comment-display-btn" href="#">{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{%endif%}</a>
          | {% endif %}

          {% if user.is_authenticated %}
          <a class="comment-reply-btn" href="#">Reply</a> |
          {% endif %}
          <a href="{{ comment.get_absolute_url }}">Thread</a>
          {% if comment.user == request.user or request.user.is_superuser or comment.content_object.user == request.user %}
          | <a href="{{ comment.get_delete_url }}">Delete</a>
          {% endif %}
        </footer>

        <div class="comment-reply">
        {% if comment.children %}
          {% for child_comment in comment.children %}
            <blockquote>
              {{ child_comment.content }}
              <footer>
                by <strong>{{ child_comment.user|capfirst }}</strong>{%if child_comment.user == instance.user%}<span class="badge">AUTH</span>{%endif%}
                | {{ child_comment.timestamp|timesince }} ago
                {% if child_comment.user == request.user or request.user.is_superuser %}
                | <a href="{{ child_comment.get_delete_url }}">Delete</a>
                {% endif %}
              </footer>
            </blockquote>
          {% endfor %}
        {% endif %}
        </div>

        <div class="comment-reply-form">
        {% if user.is_authenticated %}
        <form method="post">
          {% csrf_token %}
          {{ comment_form|crispy }}
          <input type="hidden" name="parent_id" value="{{ comment.id }}">
          <input class="btn btn-primary" type="submit" value="Reply">
        </form>
        {% endif %}
        </div>


      </blockquote>
    {% endfor %}
    {% endif %}

  </div>


</div>

{% endblock %}



{% block body_extra %}

<script type="text/javascript">

  $(document).ready(function(){

    $(".comment-reply-btn").click(function(event){
      event.preventDefault();
      $(this).parent().next().next(".comment-reply-form").fadeToggle();
    });

    $(".comment-display-btn").click(function(event){
      event.preventDefault();
      $(this).parent().next(".comment-reply").fadeToggle();
    });
  });
</script>

{% endblock body_extra %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }} {% endblock %}

{% block head_extra %}{{ form.media }}{% endblock %}


{% block body %}

<div class="row">

<div class="col-sm-5 col-sm-offset-0">

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="{{ title }}">
  </form>
</div>


<div class="col-sm-5 col-sm-offset-1">

  <h1 class="preview-title"></h1>
  <br><br>

  <p class="preview-content post-content"></p>

</div>


</div>

{% endblock body %}


{% block body_extra %}

<script type="text/javascript">

  $(document).ready(function(){

    title = $("#id_title")
    content = $("#id_content")

    function setTitle(title) {
      $(".preview-title").html(title.val());
    }

    function setContent(content) {
      markedContent = marked(content.val());
      $(".preview-content").html(markedContent);
    }

    setTitle(title);
    setContent(content);

    title.keyup(function(){
      setTitle($(this));
    });

    content.keyup(function(){
      setContent($(this))
    });
  });

</script>

{% endblock body_extra %}